const dealData = [
    {
      "pos": 11,
      "url": "/Gloria-Vanderbilt-Womens-Classic-Tapered/dp/B00021NY1O/ref=sr_1_11?keywords=deal+of+the+day&qid=1698273518&sr=8-11",
      "asin": "B00021NY1O",
      "price": 10,
      "title": "Women's Classic Amanda High Rise Tapered Jean",
      "rating": 4.3,
      "currency": "USD",
      "is_prime": false,
      "url_image": "https://m.media-amazon.com/images/I/51Q-9t61AfL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 10,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 93298,
      "is_amazons_choice": false,
      "price_strikethrough": 48,
      "shipping_information": "FREE delivery on $35 shipped by Amazon."
    },
    {
      "pos": 36,
      "url": "/Rimmel-Coverage-Kiss-Proof-Waterproof-Lipstick/dp/B072LQYKG4/ref=sr_1_36?keywords=deal+of+the+day&qid=1698273518&sr=8-36",
      "asin": "B072LQYKG4",
      "price": 1.18,
      "title": "London Stay Matte Liquid Lip Color with Full Coverage Kiss-Proof Waterproof Matte Lipstick Formula that Lasts 12 Hours - 810 Plum This Show, .21oz",
      "rating": 4.1,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/512LsmzKdjL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 1.18,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "2K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 12872,
      "is_amazons_choice": false,
      "price_strikethrough": 5.49,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 47,
      "url": "/COZSINOOR-Queen-Cooling-Pillows-Sleeping/dp/B0CC8ZWB4B/ref=sr_1_47?keywords=deal+of+the+day&qid=1698273518&sr=8-47",
      "asin": "B0CC8ZWB4B",
      "price": 28.48,
      "title": "COZSINOOR Queen Size Cooling Bed Pillows for Sleeping: Hotel Quality, Set of 2 - Down Alternative Microfiber Filled for Back, Stomach, Side Sleepers, Breathable, and Skin-Friendly",
      "rating": 4.3,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71YUmDRY4RL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 28.48,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "6K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 4923,
      "is_amazons_choice": false,
      "price_strikethrough": 96.99,
      "shipping_information": "FREE delivery Tue, Oct 31 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 28,
      "url": "/APHERMA-Massage-Athletes-Handheld-Massager/dp/B09P1DV7D8/ref=sr_1_28?keywords=deal+of+the+day&qid=1698273518&sr=8-28",
      "asin": "B09P1DV7D8",
      "price": 18.99,
      "title": "APHERMA Massage Gun, Muscle Massage Gun for Athletes Handheld Electric Deep Tissue Back Massager, Percussion Massage Device for Pain Relief with 30 Speed Levels 9 Heads",
      "rating": 4.5,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61DNkkzqe8L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 18.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "10K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 5577,
      "is_amazons_choice": false,
      "price_strikethrough": 49.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 7,
      "url": "/Fowooyeen-Silicone-Stainless-Cleaning-Ventilated/dp/B0B8HNBKQ4/ref=sr_1_7?keywords=deal+of+the+day&qid=1698273518&sr=8-7",
      "asin": "B0B8HNBKQ4",
      "price": 7.99,
      "title": "Fowooyeen Toilet Brush and Holder Set, Silicone Toilet Bowl Brush with Stainless Steel Handle, Toilet Cleaning Brush with Ventilated Drying Holder White",
      "rating": 4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/612nPLpSnoL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 7.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 3466,
      "is_amazons_choice": false,
      "price_strikethrough": 19.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 16,
      "url": "/Scissors-Titanium-Multipurpose-Comfort-Grip-Handles/dp/B07H3QKN2Z/ref=sr_1_16?keywords=deal+of+the+day&qid=1698273518&sr=8-16",
      "asin": "B07H3QKN2Z",
      "price": 7.64,
      "title": "Scissors, iBayam 8\" All Purpose Scissors Bulk 3-Pack, Ultra Sharp 2.5mm Thick Blade Shears Comfort-Grip Scissors for Office Desk Accessories Sewing Fabric Home Craft School Supplies, Right/Left Handed",
      "rating": 4.8,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61eT3wcT+KL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 7.64,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "20K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 69914,
      "is_amazons_choice": false,
      "price_strikethrough": 18.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 48,
      "url": "/Fitting-Migraine-Headache-Therapy-Tension/dp/B09HVD9C45/ref=sr_1_48?keywords=deal+of+the+day&qid=1698273518&sr=8-48",
      "asin": "B09HVD9C45",
      "price": 16.95,
      "title": "Migraine Relief Cap Ice Head Wrap Headache and Migraine Hat | Headache Relief with Hot/Cold Gel Head Ice Pack with Face and Eye Headache Mask Compress Black",
      "rating": 4.6,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/51dLq2cEkFL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 16.95,
      "is_sponsored": false,
      "manufacturer": "",
      "pricing_count": 1,
      "reviews_count": 8485,
      "is_amazons_choice": false,
      "price_strikethrough": 39.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 31,
      "url": "/RAYONNER-Lighter-Electric-Candle-Rechargeable/dp/B09525CGNJ/ref=sr_1_31?keywords=deal+of+the+day&qid=1698273518&sr=8-31",
      "asin": "B09525CGNJ",
      "price": 6.99,
      "title": "RAYONNER Lighter Electric Lighter Candle Lighter Rechargeable USB Lighter Arc Lighter Rose Gold",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61dc+VZSD0L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 6.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "10K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 8956,
      "is_amazons_choice": false,
      "price_strikethrough": 15.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 42,
      "url": "/LovesTown-Alphabet-Building-Letters-Childrens/dp/B06WXXC26S/ref=sr_1_42?keywords=deal+of+the+day&qid=1698273518&sr=8-42",
      "asin": "B06WXXC26S",
      "price": 6.99,
      "title": "LOVESTOWN Alphabet Jigsaw Puzzle, Building Blocks Animal Wooden Puzzle, Wooden Snake Letters Numbers Block Toys for Kids Birthday Gifts",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71bF5bJca0L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 6.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "4K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 3030,
      "is_amazons_choice": false,
      "price_strikethrough": 15.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 12,
      "url": "/Playtex-Womens-Ultimate-Support-White/dp/B00551OP0A/ref=sr_1_12?keywords=deal+of+the+day&qid=1698273518&sr=8-12",
      "asin": "B00551OP0A",
      "price": 17.99,
      "title": "Women's 18-Hour Ultimate Lift Wireless Full-Coverage Bra with Everyday Comfort, Single Or 2-Pack",
      "rating": 4.2,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/717KolJLtWL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 17.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 72597,
      "is_amazons_choice": false,
      "price_strikethrough": 39,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 23,
      "url": "/Outdoor-Brightness-Tempered-Sensitive-Inductor/dp/B09YXPKGY2/ref=sr_1_23?keywords=deal+of+the+day&qid=1698273518&sr=8-23",
      "asin": "B09YXPKGY2",
      "price": 29.99,
      "title": "Solar Lights Outdoor, 3 Head Solar Motion Lights Outdoor with 2500LM 218 LEDs High Brightness, Built-in Bigger Tempered Glass Solar Panel, Sensitive PIR Motion Inductor(2-Pack)",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71pKj-3o7PL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 29.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 3958,
      "is_amazons_choice": false,
      "price_strikethrough": 64.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 38,
      "url": "/LuxClub-Friendly-Hypoallergenic-Anti-Bacteria-Washable/dp/B07141228M/ref=sr_1_38?keywords=deal+of+the+day&qid=1698273518&sr=8-38",
      "asin": "B07141228M",
      "price": 27.96,
      "title": "LuxClub 6 PC Queen Sheet Set, Bed Sheets Queen Size, Deep Pockets 18\" Eco Friendly Wrinkle Free Cooling Bed Sheets Machine Washable Hotel Bedding Silky Soft - Light Teal Queen",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/81thSQ6DIfL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 27.96,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 175148,
      "is_amazons_choice": false,
      "price_strikethrough": 56.99,
      "shipping_information": "FREE delivery Tue, Oct 31 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 13,
      "url": "/Womens-Winter-Socks-Casual-Christmas/dp/B07H3NN3LC/ref=sr_1_13?keywords=deal+of+the+day&qid=1698273518&sr=8-13",
      "asin": "B07H3NN3LC",
      "price": 9.99,
      "title": "Womens Winter Socks Gift Box Free Size Thick Wool Soft Warm Casual Socks for Women Socks Christmas Gifts",
      "rating": 4.7,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71YaDbixJ1L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 9.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "5K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 17492,
      "is_amazons_choice": false,
      "price_strikethrough": 19.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 9,
      "url": "/Electric-Toothbrushes-Adults-Toothbrush-Rechargeable/dp/B09PQJWK1Q/ref=sr_1_9?keywords=deal+of+the+day&qid=1698273518&sr=8-9",
      "asin": "B09PQJWK1Q",
      "price": 19.99,
      "title": "Sonic Electric Toothbrushes for Adults, 8 Brush Heads Electric Toothbrush with 40000 VPM Deep Clean 5 Modes, Rechargeable Toothbrushes Fast Charge 4 Hours Last 30 Days",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71FeLi5ZW5L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 19.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "10K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 3935,
      "is_amazons_choice": false,
      "price_strikethrough": 39.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 37,
      "url": "/Fab-totes-Containers-Organizing-Organization/dp/B092ZDHJMN/ref=sr_1_37?keywords=deal+of+the+day&qid=1698273518&sr=8-37",
      "asin": "B092ZDHJMN",
      "price": 21.65,
      "title": "Fab totes 6 Pack Clothes Storage, Foldable Blanket Storage Bags, Storage Containers for Organizing Bedroom, Closet, Clothing, Comforter, Organization and Storage with Lids and Handle, Grey",
      "rating": 4.3,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71MQDqctnOL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 21.65,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "50K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 18207,
      "is_amazons_choice": false,
      "price_strikethrough": 41.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 10,
      "url": "/INSSL-Pillowcase-Mulberry-Comfortable-Breathable/dp/B0836FPCWZ/ref=sr_1_10?keywords=deal+of+the+day&qid=1698273518&sr=8-10",
      "asin": "B0836FPCWZ",
      "price": 11.99,
      "title": "INSSL Silk Pillowcase for Women, Mulberry Silk Pillowcase for Hair and Skin and Stay Comfortable and Breathable During Sleep (Standard, Coral)",
      "rating": 4.5,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61+xGfaOa0L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 11.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 7842,
      "is_amazons_choice": false,
      "price_strikethrough": 22.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 19,
      "url": "/Extender-Protector-Charger-Outlets-3-Sided/dp/B09ZKZYBZX/ref=sr_1_19?keywords=deal+of+the+day&qid=1698273518&sr=8-19",
      "asin": "B09ZKZYBZX",
      "price": 13.59,
      "title": "Mifaso Wall Outlet Extender with Shelf and Night Light,Surge Protector, Charger 5 USB Outlets 3 Ports 1 C Wide Space 3-Sided Power Strip Multi Plug Outlets…",
      "rating": 4.5,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/511RHXivY1L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 13.59,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "6K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 6496,
      "is_amazons_choice": false,
      "price_strikethrough": 25.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 22,
      "url": "/RUNBOX-Wallet-Blocking-Pocket-Minimalist/dp/B09M3Y8QZY/ref=sr_1_22?keywords=deal+of+the+day&qid=1698273518&sr=8-22",
      "asin": "B09M3Y8QZY",
      "price": 20.99,
      "title": "Slim Wallets for Men - Leather Money Clip Mens Wallet - RFID Blocking Front Pocket Bifold Wallet - Minimalist Credit Card Holder with Gift Box",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71m5hW2hMCL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 20.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "4K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 4319,
      "is_amazons_choice": false,
      "price_strikethrough": 39.97,
      "shipping_information": "FREE delivery Tue, Oct 31 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 14,
      "url": "/Multipurpose-Standard-leveler-cabinets-AikTryee/dp/B07WP4165D/ref=sr_1_14?keywords=deal+of+the+day&qid=1698273518&sr=8-14",
      "asin": "B07WP4165D",
      "price": 9.98,
      "title": "Laser Level Line Tool, Multipurpose Laser Level Kit Standard Cross Line Laser level Laser Line leveler Beam Tool with Metric Rulers 8ft/2.5M for Picture Hanging cabinets Tile Walls by AikTryee.",
      "rating": 4.2,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71HOVTfoB4L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 9.98,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "2K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 9380,
      "is_amazons_choice": false,
      "price_strikethrough": 18.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 8,
      "url": "/LOreal-Paris-Voluminous-Original-Waterproof/dp/B004BCXEF6/ref=sr_1_8?keywords=deal+of+the+day&qid=1698273518&sr=8-8",
      "asin": "B004BCXEF6",
      "price": 5.96,
      "title": "Makeup Voluminous Original Volume Building Waterproof Mascara, Carbon Black, 0.23 Fl Oz",
      "rating": 4.2,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61nWOIV1JnL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 5.96,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "10K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 20829,
      "is_amazons_choice": false,
      "price_strikethrough": 10.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by Amazon"
    },
    {
      "pos": 4,
      "url": "/OLANLY-Chenille-Bathroom-Absorbent-Non-Slip/dp/B0BC3PTLKN/ref=sr_1_4?keywords=deal+of+the+day&qid=1698273518&sr=8-4",
      "asin": "B0BC3PTLKN",
      "price": 8.99,
      "title": "OLANLY Bathroom Rug, Extra Soft Chenille Thick Absorbent Shaggy Mat, Non-Slip Machine Wash Dry Plush Bath Mats for Bathroom, Tub and Shower (24 x 16 Inch, Black)",
      "rating": 4.2,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/81xJAwmRZIL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 8.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 1568,
      "is_amazons_choice": false,
      "price_strikethrough": 15.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 25,
      "url": "/RUNBOX-Wallet-Capacity-Blocking-Bifold/dp/B09M3Z63QP/ref=sr_1_25?keywords=deal+of+the+day&qid=1698273518&sr=8-25",
      "asin": "B09M3Z63QP",
      "price": 17.99,
      "title": "Men's Wallets Slim Rfid Leather 2 ID Window With Gift Box Men's Accessories",
      "rating": 4.5,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71CHmL6xZqL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 17.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "6K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 3288,
      "is_amazons_choice": false,
      "price_strikethrough": 29.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 5,
      "url": "/Hanes-womens-Cotton-briefs-underwear/dp/B00FZR1IHC/ref=sr_1_5?keywords=deal+of+the+day&qid=1698273518&sr=8-5",
      "asin": "B00FZR1IHC",
      "price": 10.47,
      "title": "Women's Hi-Cut Panties Pack, Lightweight Cotton Hi-Cuts, 10-Pack (Retired, Colors May Vary)",
      "rating": 4.2,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71l0+-t+f5L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 10.47,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "200+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 27136,
      "is_amazons_choice": false,
      "price_strikethrough": 17,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 6,
      "url": "/OLANLY-Moisture-Absorbent-Non-Slip-Microfiber/dp/B0BWT84GZ7/ref=sr_1_6?keywords=deal+of+the+day&qid=1698273518&sr=8-6",
      "asin": "B0BWT84GZ7",
      "price": 9.99,
      "title": "OLANLY Dog Door Mat for Muddy Paws, Absorbs Moisture and Dirt, Non-Slip Washable Mat, Quick Dry Microfiber, Mud Mat for Dogs, Entry Indoor Door Mat for Inside Floor(30x20 Inches, Grey)",
      "rating": 4.6,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/91Gs5TC9Q7L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 9.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "3K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 695,
      "is_amazons_choice": false,
      "price_strikethrough": 15.99,
      "shipping_information": "FREE delivery Tue, Oct 31 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 24,
      "url": "/FLUESTON-Writing-Christmas-Birthday-Dinosaur/dp/B0CDBYW6LH/ref=sr_1_24?keywords=deal+of+the+day&qid=1698273518&sr=8-24",
      "asin": "B0CDBYW6LH",
      "price": 19.99,
      "title": "FLUESTON Toys LCD Writing Tablet Toddler,Toys for Boys Girls 3 4 5 6 7 8year,8.8 Inch 3pcs in 1 Pack Drawing Pad Toy Christmas Birthday Gifts for Kids,Drawing Tablet Doodle Board Cute Dinosaur Unicorn",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71mBl9xccpL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 19.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "5K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 1868,
      "is_amazons_choice": false,
      "price_strikethrough": 29.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 32,
      "url": "/Cleaner-Vacuum-Attachment-Remover-Washer/dp/B08QJ8SHGV/ref=sr_1_32?keywords=deal+of+the+day&qid=1698273518&sr=8-32",
      "asin": "B08QJ8SHGV",
      "price": 13.98,
      "title": "Sealegend 2 Pack Dryer Vent Cleaner Kit Vacuum Hose Attachment, Dryer Lint Cleaner Kit Lint Remover Tools Hoses with Adapter",
      "rating": 4.1,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61gek+N-sRL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 13.98,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "2K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 8916,
      "is_amazons_choice": false,
      "price_strikethrough": 19.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 41,
      "url": "/Hanes-Womens-Sweatpant-Heather-X-Large/dp/B0169P8PCO/ref=sr_1_41?keywords=deal+of+the+day&qid=1698273518&sr=8-41",
      "asin": "B0169P8PCO",
      "price": 12.95,
      "title": "Women’s Sweatpants, ComfortSoft EcoSmart Open Leg Fleece Sweatpants",
      "rating": 4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71slb+CkbuL._AC_UL320_.jpg",
      "best_seller": true,
      "price_upper": 12.95,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "3K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 63725,
      "is_amazons_choice": false,
      "price_strikethrough": 18,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 40,
      "url": "/BlissTotes-Clothing-Organizer-Reinforced-Collapsible/dp/B09Y55BJRZ/ref=sr_1_40?keywords=deal+of+the+day&qid=1698273518&sr=8-40",
      "asin": "B09Y55BJRZ",
      "price": 19.99,
      "title": "BlissTotes Storage Clothing Bags Storage Clothes Organizer with Reinforced Handle Sturdy Fabric Clear Window for Blankets, Bedding, Collapsible with Sturdy Zipper, 6 Pack, 60L, Grey",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/81NEtFLBoOL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 19.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "3K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 1269,
      "is_amazons_choice": false,
      "price_strikethrough": 26.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 34,
      "url": "/Under-Armour-Sportstyle-T-Shirt-X-Large/dp/B077XQXJCJ/ref=sr_1_34?keywords=deal+of+the+day&qid=1698273518&sr=8-34",
      "asin": "B077XQXJCJ",
      "price": 18.75,
      "title": "Men's Sportstyle Left Chest Short Sleeve T-Shirt",
      "rating": 4.6,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/51s4Mv1ac3L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 18.75,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "1K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 25693,
      "is_amazons_choice": false,
      "price_strikethrough": 25,
      "shipping_information": "FREE delivery Tue, Oct 31 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 26,
      "url": "/Certified-Lightning-Charging-Compatible-8-multicolor/dp/B0C4F71FWV/ref=sr_1_26?keywords=deal+of+the+day&qid=1698273518&sr=8-26",
      "asin": "B0C4F71FWV",
      "price": 9.97,
      "title": "[Apple MFi Certified] iPhone Charger, 6Pack(3/3/6/6/6/10 FT) Lightning Cable Apple Charging Fast High Speed USB Compatible 14/13/12/11 Pro Max/XS MAX/XR/XS/X/8-multicolor",
      "rating": 4.5,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/81t503R1wWL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 9.97,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "3K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 784,
      "is_amazons_choice": false,
      "price_strikethrough": 12.99,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 39,
      "url": "/Hydration-Electrolyte-Antioxidants-Naturally-Single-Serving/dp/B0BQRV1FHH/ref=sr_1_39?keywords=deal+of+the+day&qid=1698273518&sr=8-39",
      "asin": "B0BQRV1FHH",
      "price": 6.99,
      "title": "PRIME Hydration Sticks Blue Raspberry | Hydration Powder Single Serve Sticks | Electrolyte Powder on the go | 0 Sugar | Caffeine Free | Vegan | 6 Pack",
      "rating": 4.3,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/61r2hyIU2gL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 6.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "7K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 613,
      "is_amazons_choice": false,
      "price_strikethrough": 8.98,
      "shipping_information": "FREE delivery Mon, Oct 30 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 27"
    },
    {
      "pos": 17,
      "url": "/SUUSON-Mount【Upgraded】-【Bumpy-Friendly】-Dashboard-Windshield/dp/B0CH14PBX9/ref=sr_1_17?keywords=deal+of+the+day&qid=1698273518&sr=8-17",
      "asin": "B0CH14PBX9",
      "price": 13.59,
      "title": "SUUSON Car Phone Holder Mount【Upgraded】-【Bumpy Roads Friendly】 Phone Mount for Car Dashboard Windshield Air Vent 3 in 1,Hand Free Mount for iPhone 15 14 13 Pro Max Samsung All Cell Phones (Black)",
      "rating": 4.4,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/71PKoUZqi4L._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 13.59,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "10K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 11258,
      "is_amazons_choice": false,
      "price_strikethrough": 16.99,
      "shipping_information": "FREE delivery Wed, Nov 1 on $35 of items shipped by Amazon"
    },
    {
      "pos": 1,
      "url": "/Backpack-Expandable-Backpacks-Resistant-Weekender/dp/B0B6GCHWW2/ref=sr_1_1?keywords=deal+of+the+day&qid=1698273518&sr=8-1",
      "asin": "B0B6GCHWW2",
      "price": 44.99,
      "title": "Carry on Travel Backpack, Extra Large 40L Flight Approved for Men & Women,Expandable Large Suitcase Backpacks With 4 Packing Cubes,Water Resistant Luggage Daypack Business Weekender Bag,Grey",
      "rating": 4.7,
      "currency": "USD",
      "is_prime": true,
      "url_image": "https://m.media-amazon.com/images/I/81vEn1k0XmL._AC_UL320_.jpg",
      "best_seller": false,
      "price_upper": 44.99,
      "is_sponsored": false,
      "manufacturer": "",
      "sales_volume": "3K+ bought in past month",
      "pricing_count": 1,
      "reviews_count": 2382,
      "is_amazons_choice": false,
      "price_strikethrough": 54.99,
      "shipping_information": "FREE delivery Mon, Oct 30 Or fastest delivery Fri, Oct 27"
    }
  ]

  module.exports = dealData;